### ISSUE TITLE
FDCAN doesn't work with new release

### ISSUE THREAD

**Issue by CuboiLeo** [STMicroelectronics/stm32h7xx_hal_driver#74]
FDCAN doesn't work with the current release; it sends out empty messages. I found the problem in stm32h7xx_hal_fdcan.c on line 6223 and line 6235; pTxHeader ->DataLength being 0x00080000 needs to shift 16 bits to the right. After reverting this to the prior release, FDCAN can work now. 

Please check whether this is a bug or if I missed some setups.

<img width="974" alt="issue" src="https://github.com/user-attachments/assets/9ae38de7-2085-4b6d-b1a4-087901f8d87b">

**Comment by KRASTM** [comment]
Hello @CuboiLeo,

Thank you for the report.

Just to be sure, you are using the v1.11.3 version for HAL, and hal_fdcan.c & hal_fdcan.h files?
Please, can you share more details about your project and/or config?

In the meanwhile, we will try to analyze further the issue

With regards,

**Comment by KRASTM** [comment]
Hello @CuboiLeo,

I checked with our team, the change is due to a fix, because in the For loop we need the value of data length and for pTxHeader->DataLenght, we need the value in the register, so that's why we have shifted to the left (pTxHeader->DataLength << 16U).

In the last version, the **FDCAN_DLC_BYTES_x** in header file was already left shifted, and we have right shift in the function FDCAN_CopyMessageToRAM(), but now we do not need to do the shift to have the value, it's already shifted.
<img width="903" alt="DLC" src="https://github.com/user-attachments/assets/faf55c9a-fb48-4d15-936a-39c478426e69">

I did test an example with STM32H743i eval board and it works fine.

So, I suggest checking the motor driver files or your config, you can also check STM32H7xx FDCAN examples for more details.

Please, allow me to close this issue, thank you for your comprehension.

with regards,
